trigger:
-  main


variables:
  brahim:  'helloyeeessiiiiir'



stages:

- stage: build

  jobs:
    - job: buildi_baabaha
      variables:
          hhh:  "hohoh"
      steps:
        - script: |
                cd order-service
                ls -l .
                docker build  -t image01 .
                docker images 

        - task: Docker@2
          displayName: 'Build and Push Docker Image'
          inputs:
                   command: buildAndPush
                   containerRegistry: 'connexion vers ACR'
                   repository: 'order-service'
                   Dockerfile: 'order-service/Dockerfile'
                