trigger:
-  main


variables:
  brahim:  'helloyeeessiiiiir'



stages:

- stage: build

  jobs:
    - job: buildi_baabaha
      container:
          image: nginx
      variables:
          hhh:  "hohoh"
      steps:
        - script: |
                cd order-service
                ls -l .
                docker build  -t image01 .
